# Generated by Django 5.0.6 on 2024-06-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_orders_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
